name: Generate Content JSON

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  CONTENT_SERVER: "${{ secrets.CONTENT_SERVER }}"

jobs:
  generate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate content.json
        run: node .github/workflows/generate-content-json.mjs

      - name: Fetch latest changes
        run: git pull origin main

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
